CREATE DATABASE JOINT 

--Alunos (MAT, nome, endereço, cidade)
CREATE TABLE ALUNO(
CODALUNO SERIAL PRIMARY KEY,
NOMEALUNO VARCHAR(80) NOT NULL,
ENDERECO VARCHAR (120) NOT NULL,
CIDADE VARCHAR(120) NOT NULL 
);
DROP CONSTRAINT CIDADE;
INSERT INTO ALUNO(CODALUNO,NOMEALUNO,ENDERECO,CIDADE) VALUES(2015010101,'JOSE DE ALENCAR', 'RUA DAS ALMAS', 'NATAL') 
INSERT INTO ALUNO(CODALUNO,NOMEALUNO,ENDERECO,CIDADE) VALUES(2015010102, 'JOÃO JOSÉ', 'AVENIDA RUY CARNEIRO', 'JOÃO PESSOA') 
INSERT INTO ALUNO(CODALUNO,NOMEALUNO,ENDERECO,CIDADE) VALUES(2015010103, 'MARIA JOAQUINA', 'RUA CARROSSEL', 'RECIFE') 
INSERT INTO ALUNO(CODALUNO,NOMEALUNO,ENDERECO,CIDADE) VALUES(2015010104, 'MARIA DAS DORES', 'RUA DAS LADEIRAS', 'FORTALEZA') 
INSERT INTO ALUNO(CODALUNO,NOMEALUNO,ENDERECO,CIDADE) VALUES(2015010105, 'JOSUÉ CLAUDINO DOS SANTOS', 'CENTRO', 'NATAL') 
INSERT INTO ALUNO(CODALUNO,NOMEALUNO,ENDERECO,CIDADE) VALUES(2015010106, 'JOSUÉLISSON CLAUDINO DOS SANTOS', 'CENTRO', 'NATAL') 

--Disciplinas (COD_DISC, nome_disc, carga_hor)
CREATE TABLE DISCIPLINAS(
CODDISC SERIAL PRIMARY KEY,
NOMEDISC VARCHAR(120) NOT NULL UNIQUE,
CARGAHOR VARCHAR(15) NOT NULL
);
INSERT INTO DISCIPLINAS(NOMEDISC,CARGAHOR) VALUES('BANCO DE DADOS', '100') 
INSERT INTO DISCIPLINAS(NOMEDISC,CARGAHOR) VALUES('PROGRAMAÇÃO COM ACESSO A BANCO DE DADOS', '100')
INSERT INTO DISCIPLINAS(NOMEDISC,CARGAHOR) VALUES('AUTORIA WEB', '50')  
INSERT INTO DISCIPLINAS(NOMEDISC,CARGAHOR) VALUES('ENGENHARIA DE SOFTWARE', '80') 
SELECT * FROM DISCIPLINAS
--Professores (COD_PROF, nome, endereço, cidade)
CREATE TABLE PROFESSORES(
CODPROF SERIAL PRIMARY KEY,
NOMEPROF VARCHAR(80) NOT NULL,
ENDERECO VARCHAR(120) NOT NULL,
CIDADE VARCHAR(120) NOT NULL 
);
INSERT INTO PROFESSORES(CODPROF,NOMEPROF,ENDERECO,CIDADE) VALUES(212131, 'NICKERSON FERREIRA', 'RUA MANAÍRA', 'JOÃO PESSOA')
INSERT INTO PROFESSORES(CODPROF,NOMEPROF,ENDERECO,CIDADE) VALUES(122135, 'ADORILSON BEZERRA', 'AVENIDA SALGADO FILHO', 'NATAL')
INSERT INTO PROFESSORES(CODPROF,NOMEPROF,ENDERECO,CIDADE) VALUES(192011, 'DIEGO OLIVEIRA', 'AVENIDA ROBERTO FREIRE', 'NATAL') 

/*Turma (COD_DISC, COD_TURMA, COD_PROF, ANO, horário)
 COD_DISC referencia Disciplinas
 COD_PROF referencia Professores*/
CREATE TABLE TURMA(
CODTURMA SERIAL PRIMARY KEY, 	 
CODDISC_FK INTEGER REFERENCES DISCIPLINAS(CODDISC),
CODPROF_FK INTEGER REFERENCES PROFESSORES(CODPROF),
ANO CHAR(15) NOT NULL,
HORARIO CHAR(15) NOT NULL
);
/*(BD, 1, 212131, 2015, 11H-12H)
(BD, 2, 212131, 2015, 13H-14H)
(POO, 1, 192011, 2015, 08H-09H)
(WEB, 1, 192011, 2015, 07H-08H)
(ENG, 1, 122135, 2015, 10H-11H)*/
/*Histórico (MAT, COD_DISC, COD_TURMA, COD_PROF, ANO, frequência, nota)
MAT referencia Alunos
COD_DISC, COD_TURMA, COD_PROF, ANO referencia Turma*/
CREATE TABLE HISTORICO(
CODALUNO_FK INTEGER REFERENCES ALUNO(CODALUNO),
CODDISC_FK INTEGER REFERENCES DISCIPLINAS(CODDISC),
CODTURMA_FK INTEGER REFERENCES TURMA(CODTURMA),
CODPROF_FK INTEGER REFERENCES PROFESSORES(CODPROF),
ANO CHAR(5) NOT NULL,
FREQUENCIA NUMERIC(10,2) NOT NULL,
NOTA FLOAT NOT NULL
);